### ISSUE TITLE
NotSupportedException method 

### ISSUE THREAD

**Issue by saramgsilva** [Cimbalino/Cimbalino-Toolkit#12]
Hello,

I found some methods that are not supported in one platform, for example the VibrationService for Win8.1. In my opinion this class should not be exist in Win8.1. or if exist like now, should be added to the summary something like

"Supported in WP8.0 and WP8.1"
"NotSupported in Win8.1"

this will appear in tooltip when we call the method and in documentation generated by Ghostdoc or 	
Sandcastle.

**Comment by PedroLamas** [comment]
This info is now part of the SandCastle generated documentation!
