### ISSUE TITLE
ForegroundColor & BackgroundColor are reset

### ISSUE THREAD

**Issue by dkhmelenko** [Cimbalino/Cimbalino-Toolkit#31]
There is an issue with `ApplicationBarBehaviour`.
I have to pages A and B. Page A has appbar, page B - doesn't. Page A has the following code for appBar.
```
<i:Interaction.Behaviors>
        <cimbalinoTk:ApplicationBarBehavior 
                                          BackgroundColor="{StaticResource BackgroundLightGrayColor}" 
                                          ForegroundColor="{StaticResource FontGrayColor}">
            <cimbalinoTk:ApplicationBarIconButton 
                IconUri="/Assets/AppBar/appbar.search.png"
                Text="search"
                Command="{Binding SearchCommand}"/>
        </cimbalinoTk:ApplicationBarBehavior>
</i:Interaction.Behaviors>
```
When I navigated first time on the page A, background and foreground colors are applied properly. 
But if I go to page B and then press Back button, the colors on the application bar on the page A are reset.
What can be the reason?

**Comment by PedroLamas** [comment]
I've been trying to reproduce this issue, haven't been able do far...

Have you attached the behavior to the `PhoneApplicationPage` or to the `LayoutRoot` element? I advise to do it to the root element.

Also, make sure you don't have any ApplicationBar set on the page, just the behavior!

**Comment by dkhmelenko** [comment]
I attached to `PhoneApplicationPage`. When I tried to attach it to they `LayoutRoot`, I've got the following error:
```
InnerException	{System.InvalidOperationException: Cannot attach type "ApplicationBarBehavior" to type "Grid". Instances of type "ApplicationBarBehavior" can only be attached to objects of type "PhoneApplicationPage".
   at System.Windows.Interactivity.Behavior.Attach(DependencyObject dependencyObject)
   at System.Windows.Interactivity.BehaviorCollection.ItemAdded(Behavior item)
   at System.Windows.Interactivity.AttachableCollection`1.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.DependencyObjectCollection`1.TryCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.DependencyObjectCollection`1.System.Collections.IList.Add(Object value)
   at MS.Internal.XamlManagedRuntimeRPInvokes.Add(XamlQualifiedObject& qoCollection, XamlPropertyToken inCollectionProperty, XamlQualifiedObject& inValue)}	System.Exception {System.InvalidOperationException}
```

My app doesn't any any ApplicationBar. Only the code I posted in the previous post.

**Comment by PedroLamas** [comment]
This may be some incompatibility with another framework/toolkit... what are you using besides Cimbalino Toolkit?

**Comment by dkhmelenko** [comment]
I created empty project, where only Cimbalino library is used. Still have this problem.
Could you look please at my simple example and tell me where I'm wrong?
```
<phone:PhoneApplicationPage
    x:Class="TestCimbalino.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:phone="clr-namespace:Microsoft.Phone.Controls;assembly=Microsoft.Phone"
    xmlns:shell="clr-namespace:Microsoft.Phone.Shell;assembly=Microsoft.Phone"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:cimbalino="clr-namespace:Cimbalino.Toolkit.Behaviors;assembly=Cimbalino.Toolkit"
    xmlns:i="clr-namespace:System.Windows.Interactivity;assembly=System.Windows.Interactivity"
    mc:Ignorable="d"
    FontFamily="{StaticResource PhoneFontFamilyNormal}"
    FontSize="{StaticResource PhoneFontSizeNormal}"
    Foreground="{StaticResource PhoneForegroundBrush}"
    SupportedOrientations="Portrait" Orientation="Portrait"
    shell:SystemTray.IsVisible="True">

    
    <Grid x:Name="LayoutRoot" Background="Transparent">

        <!-- App bar -->
        <i:Interaction.Behaviors>
            <cimbalino:ApplicationBarBehavior
            BackgroundColor="Red"
            ForegroundColor="Blue">
                <cimbalino:ApplicationBarIconButton
                    Text="Press"
                    Click="ApplicationBarIconButton_Click"
                />
            </cimbalino:ApplicationBarBehavior>
        </i:Interaction.Behaviors>
        
    </Grid>

</phone:PhoneApplicationPage>```

**Comment by PedroLamas** [comment]
Start by putting the whole App bar block outside (before the `Grid` element) as that is always best for page lifecycle reasons!

**Comment by PedroLamas** [comment]
Here's a small sample that I'm using to try and simulate your issue, can you please download, open in VS2013 and test it? Thanks! https://dl.dropboxusercontent.com/u/28356/gc/PhoneApp1.zip

**Comment by dkhmelenko** [comment]
That's what I did before. But then you told me to attach it to the `LayoutRoot`. Or what did you mean?

**Comment by PedroLamas** [comment]
Ah sorry about that, I choose the worst wording possible there... do attach it to the `PhoneApplicationPage` as you were correctly doing before!

**Comment by dkhmelenko** [comment]
Sorry, but seems that some of the libraries in my project breaks it. :(
And I guess I found it. I uses the library `ThemeManager`.
In App.xaml.cs I'm setting `ThemeManager.ToLightTheme();`. If I do not do that, everything works as well and app bar colors are saved. But if I change the theme, app bar colors are reset.

Sorry for disturbing one more time.

**Comment by PedroLamas** [comment]
Ah, I've seen that issue in the past! Try doing this then:

    ThemeManager.OverrideOptions = ThemeManagerOverrideOptions.SystemTrayColors;
    ThemeManager.ToLightTheme();

**Comment by dkhmelenko** [comment]
Wow! Thank you a lot!! It works!

Could you please add such specific behaviour somewhere to Wiki? That could make life easier for the other.

**Comment by PedroLamas** [comment]
Sure thing!! Probably will add this to the FAQ so it's more visible! :)
