### ISSUE TITLE
Code metrics fail if a project has classes inheriting from Cimbalino.Toolkit.Behaviors.Behavior

### ISSUE THREAD

**Issue by P2SH** [Cimbalino/Cimbalino-Toolkit#34]
Error:
````
Message: An error occurred while calculating code metrics for target file 'xxx' in project xxx. The following error was encountered while reading module 'Cimbalino.Toolkit': Assembly reference cannot be resolved: Microsoft.Xaml.Interactivity, Version=12.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
````

Tested on both WPA81 and Win81. Works fine if you build from source. Seems to happen only when using the nuget package.

**Comment by PedroLamas** [comment]
So from what I can see here, you run the code-metrics in Visual Studio and it gave you this error message?
Microsoft.Xaml.Interactivity assembly is now added through the XAML Behaviors Extension SDK, it might be related to that, but I'll run a couple of tests to confirm!

**Comment by PedroLamas** [comment]
I'm closing this as I haven't been able to reproduce the issue while using v2.0.0, but please fell free to re-open if you do!
