### ISSUE TITLE
NullReferenceException when pressing hardware back button wp10

### ISSUE THREAD

**Issue by Depechie** [Cimbalino/Cimbalino-Toolkit#41]
In a Windows 10 UWP project, I get following error in the UnhandledException of the App:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Cimbalino.Toolkit.Services.NavigationService.HandleBackKeyPress()
   at Cimbalino.Toolkit.Services.NavigationService.HardwareButtons_BackPressed(Object sender, BackPressedEventArgs e)

This happens when debugging on a Windows Phone device and pressing the hardware back button to leave the app.
When I first do a navigation to another page, the error isn't there. So just starting the app and first thing, pressing back to quit it results in the error.

Running Cimbalino toolkit beta 3 ( for UWP )

**Comment by PedroLamas** [comment]
Fixed with 6bf949e62e4c6cdc57b62842167908b05dd68075
