### ISSUE TITLE
App certification for Windows Phone 8.1 Silverlight

### ISSUE THREAD

**Issue by JohannTIM** [Cimbalino/Cimbalino-Toolkit#48]
Hello I am using your toolkit for generating pngs for images. But I get the following issue when I try to certify the app, with wp certification kit:

    This API is not supported for this application type - Api=Microsoft.Phone.Shell.CycleTileData. Module=. File=Cimbalino.Phone.Toolkit.Background.dll.
    This API is not supported for this application type - Api=Microsoft.Phone.Shell.FlipTileData. Module=. File=Cimbalino.Phone.Toolkit.Background.dll.
    This API is not supported for this application type - Api=Microsoft.Phone.Shell.IconicTileData. Module=. File=Cimbalino.Phone.Toolkit.Background.dll.
    This API is not supported for this application type - Api=Microsoft.Phone.Shell.ShellTile. Module=. File=Cimbalino.Phone.Toolkit.Background.dll.
    This API is not supported for this application type - Api=Microsoft.Phone.Shell.ShellTileData. Module=. File=Cimbalino.Phone.Toolkit.Background.dll.
    This API is not supported for this application type - Api=Microsoft.Phone.Shell.ShellToast. Module=. File=Cimbalino.Phone.Toolkit.Background.dll.
    This API is not supported for this application type - Api=Microsoft.Phone.Shell.StandardTileData. Module=. File=Cimbalino.Phone.Toolkit.Background.dll.
    This API is not supported for this application type - Api=Microsoft.Phone.Shell.ShellTile. Module=. File=Cimbalino.Phone.Toolkit.dll.
    This API is not supported for this application type - Api=Microsoft.Phone.Shell.ShellTileData. Module=. File=Cimbalino.Phone.Toolkit.dll.
   
The weird thing is that I am not interested in using the shell api, since I have WNS pushnotification working. Have you seen this issue before?

**Comment by PedroLamas** [comment]
Can you tell me what type of app are we talking here? Is this a WP8, Win81, WPA81, or UAP app? Are you using any background agents?

**Comment by PedroLamas** [comment]
Oh wait, this is using the "old" Cimbalino Windows Phone Toolkit, not the new Cimbalino Toolkit (which is here!)

If you're not developing for WP7, I suggest you update to the new one first! :)

**Comment by JohannTIM** [comment]
Sorry only included in the title. It is a WP8 silverlight app that has been upgraded to wp8.1 silverlight. It does not use background agents and is supporting WNS

**Comment by JohannTIM** [comment]
Ahh okay THX, I will test this! Hope you have saved my life :)
