### ISSUE TITLE
Hamburger menu expand/collapse animation

### ISSUE THREAD

**Issue by jansokoly** [Cimbalino/Cimbalino-Toolkit#53]
Is there a way to achieve that Windows 10 animation effect when opening/collapsing the hamburger menu seen in many native W10 apps like Money, Weather, etc.?

And thanks for the library!

**Comment by PedroLamas** [comment]
I guess you'll have to re-template the control and add the animations... Not ideal, but I assume that's what they did on their side for those apps!

**Comment by PedroLamas** [comment]
Correction: the animations are there for the "normal" state, all you need to do is avoid the "wide" state by setting the `HamburgerFrame.VisualStateWideMinWidth` to a large value like `int.MaxValue`

Soo n the sample code [here](https://github.com/Cimbalino/Cimbalino-Toolkit/blob/master/samples/HamburgerFrame/HamburgerFrame/App.xaml.cs#L63), just add `VisualStateWideMinWidth = int.MaxValue` on the next line and you're good to go!
