### ISSUE TITLE
Merge effort with Community Toolkit?

### ISSUE THREAD

**Issue by xied75** [Cimbalino/Cimbalino-Toolkit#57]
Dear all,

Great stuff here. I was wondering if it could benefit the UWP community even further by gradually merging the effort with https://github.com/Microsoft/UWPCommunityToolkit?

Best regards

**Comment by PedroLamas** [comment]
It's a fair comment and while there is common ground to do that, Cimbalino goes a bit further by not only supporting Windows 10, but also Windows Phone 8 and Windows 8!

There's nothing stopping people from using both in their projects as they won't collide (we've checked 😄 ), so for the moment I think we will carry on separate routes but with one eye on each side!
